export const mockAnimeDb = {
  data: [
    {
      sources: [
        'https://anilist.co/anime/142051',
        'https://myanimelist.net/anime/51478',
      ],
      title: '!NVADE SHOW!',
      type: 'SPECIAL',
      episodes: 1,
      status: 'FINISHED',
      animeSeason: {
        season: 'FALL',
        year: 2020,
      },
      picture: 'https://cdn.myanimelist.net/images/anime/1930/122178.jpg',
      thumbnail: 'https://cdn.myanimelist.net/images/anime/1930/122178t.jpg',
      synonyms: ['!nvade Show!'],
      relations: [
        'https://anilist.co/anime/101633',
        'https://myanimelist.net/anime/37869',
      ],
      tags: ['band', 'full cgi', 'music'],
    },
    {
      sources: [
        'https://anidb.net/anime/10143',
        'https://anilist.co/anime/102416',
        'https://anime-planet.com/anime/chiaki-kuriyama-0',
        'https://kitsu.io/anime/8925',
        'https://myanimelist.net/anime/20707',
        'https://notify.moe/anime/Ff1bpKmmR',
      ],
      title: '"0"',
      type: 'SPECIAL',
      episodes: 1,
      status: 'FINISHED',
      animeSeason: {
        season: 'SUMMER',
        year: 2013,
      },
      picture: 'https://cdn.myanimelist.net/images/anime/12/81160.jpg',
      thumbnail: 'https://cdn.myanimelist.net/images/anime/12/81160t.jpg',
      synonyms: [
        '"Zero"',
        'Chiaki Kuriyama - 0',
        'Chiaki Kuriyama - Zero',
        'Chiaki Kuriyama: "0"',
        'Chiaki Kuriyama: 「0」',
        '「0」',
        '栗山 千明「0」',
      ],
      relations: [],
      tags: ['female protagonist', 'music'],
    },
    {
      sources: [
        'https://anidb.net/anime/3689',
        'https://anisearch.com/anime/1789',
        'https://kitsu.io/anime/9179',
        'https://myanimelist.net/anime/25627',
        'https://notify.moe/anime/eM1-pKmiR',
      ],
      title: '"Aesop" no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu',
      type: 'MOVIE',
      episodes: 1,
      status: 'FINISHED',
      animeSeason: {
        season: 'WINTER',
        year: 1970,
      },
      picture: 'https://cdn.myanimelist.net/images/anime/3/65151.jpg',
      thumbnail: 'https://cdn.myanimelist.net/images/anime/3/65151t.jpg',
      synonyms: [
        '"いそっぷ"のおはなしより 牛とかえる',
        '"いそっぷ"のおはなしより 牛とかえる, よくばった犬',
        "From Aesop's Tales: The Bull and the Frog / The Greedy Dog",
        'From Aesop`s Tales: The Bull and the Frog / The Greedy Dog',
        '“いそっぷ”のおはなしより 牛とかえる、よくばった犬',
      ],
      relations: [],
      tags: ['fantasy', 'kids'],
    },
    {
      sources: [
        'https://anidb.net/anime/7294',
        'https://anilist.co/anime/7669',
        'https://anime-planet.com/anime/bungaku-shoujo-kyou-no-oyatsu-hatsukoi',
        'https://anisearch.com/anime/5970',
        'https://kitsu.io/anime/5078',
        'https://livechart.me/anime/5549',
        'https://myanimelist.net/anime/7669',
        'https://notify.moe/anime/oTdkpKiig',
      ],
      title: '"Bungaku Shoujo" Kyou no Oyatsu: Hatsukoi',
      type: 'OVA',
      episodes: 1,
      status: 'FINISHED',
      animeSeason: {
        season: 'FALL',
        year: 2009,
      },
      picture: 'https://cdn.myanimelist.net/images/anime/2/79900.jpg',
      thumbnail: 'https://cdn.myanimelist.net/images/anime/2/79900t.jpg',
      synonyms: [
        '"文学少女"今日のおやつ ~はつ恋~',
        'Book Girl OVA',
        'Bungaku Shoujo OVA',
        'Bungaku Shoujo: Kyou no Oyatsu - Hatsukoi',
        'Bungaku Shōjo: Kyō no Oyatsu - Hatsukoi',
        'Literature Girl',
        'Literature Girl OVA',
        'Literature Girl: Today`s Snack - First Love',
        'Буквоежка: Первая любовь',
        '“文学少女”今日のおやつ 〜はつ恋〜',
        '“文学少女”今日のおやつ ～はつ恋～',
        '文学少女 今日のおやつ 〜はつ恋〜',
      ],
      relations: [
        'https://anidb.net/anime/6959',
        'https://anidb.net/anime/7441',
        'https://anilist.co/anime/6408',
        'https://anime-planet.com/anime/bungaku-shoujo-memoire',
        'https://anime-planet.com/anime/bungaku-shoujo-movie',
        'https://kitsu.io/anime/4550',
        'https://myanimelist.net/anime/6408',
        'https://notify.moe/anime/UUie5KimR',
      ],
      tags: ['comedy', 'drama', 'fantasy', 'romance', 'school'],
    },
  ],
};
